### ISSUE TITLE
Add CodingStandard repo

### ISSUE THREAD

**Issue by TomasVotruba** [planette/commits#3]
I could not find it, so I re-introduce my request from Nette forum. I think tools would be the best fit: http://nette-commits.cz/tools

https://github.com/nette/coding-standard

What do you think?

**Comment by uestla** [comment]
Thanks for the reminder, I completely forgot about this ;-)

Glad to see the repo growing!

**Comment by TomasVotruba** [comment]
Thanks :heart:
