### ISSUE TITLE
Web nette-commits.cz not working

### ISSUE THREAD

**Issue by foxycode** [planette/commits#46]
Looks like http://nette-commits.cz is not in DNS and there's error on https://commits.planette.io

You have new address?

See https://forum.nette.org/cs/19406-commity-vsech-nette-repozitaru-pokupe?p=2#p188971

**Comment by f3l1x** [comment]
Solved.

https://forum.nette.org/cs/19406-commity-vsech-nette-repozitaru-pokupe#p131969

Thanks Tom.
