### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by f3l1x** [planette/commits#73]
Setup minimal travis CI. For example code style, phpstan or tests.

**Comment by uestla** [comment]
Basically it could be the same pipeline as in `composer ci`: https://github.com/planette/commits/blob/bbed892ced10cc5e4432cdb4242891eb7d7a8d40/composer.json#L53-L60

**Comment by adaamz** [comment]
Why not gh actions?

**Comment by f3l1x** [comment]
Hey @adaamz, thanks for pointing that out. The right question is why should we (maintainers of this and other repositories) go for Github Actions. You can elaborate on it, describe in details cons/prons and maybe we can discuss about it. Thanks.

**Comment by adaamz** [comment]
I think there are many articles, for example https://www.tomasvotruba.com/blog/2020/01/27/switch-travis-to-github-actions-to-reduce-stress/

**Comment by uestla** [comment]
I've just got travis going the way I wanted to (parallel jobs that check code itself and tester afterwards).

However, GitHub Actions look quite interesting since it's integrated directly under one "roof", I'll take a look and try to get the same configuration for it, thanks for the tip, @adaamz !

**Comment by f3l1x** [comment]
Travis is working. 👍
