### ISSUE TITLE
Footer 

### ISSUE THREAD

**Issue by f3l1x** [planette/commits#79]
It would be nice to show more info in footer.

- Link to source code
- Last synchronization

![Framework___nette_commits](https://user-images.githubusercontent.com/538058/127313449-fa1f7dfb-c5a1-41b5-a336-ae7765894e20.png)

**Comment by f3l1x** [comment]
What do you think @uestla ?

**Comment by uestla** [comment]
Definitely - timestamp of last synchronization is a nice idea.
What do you mean by the "Source code" on the screenshot?

**Comment by f3l1x** [comment]
Just link (ahref) to this repository. Let people know it's public repo.

**Comment by uestla** [comment]
I see, there's already a button Github in the navbar at the top that leads here though.
Another one in the footer is OK though :-)

**Comment by uestla** [comment]
I see, there's already a button Github in the navbar at the top that leads here.
Another one in the footer is OK though :-)

**Comment by f3l1x** [comment]
You're right. I must be blind :-D Just add please sync date somewhere.
